var messages = {

    blocks: {
        openElevator_name : 'open elevator',
        openElevator_tip : 'Open the elevator at the desired floor and indicate the direction to pick up passengers',
        openElevator_tipS : 'Open the elevator to pick up passengers',
        goToFloor_name : 'go to floor',
        goToFloor_tip : 'Send the elevator to a desired floor. Make sure you pass the floor as a parameter!',
        storeRequest_name : 'add travel request',
        storeRequest_tip : 'Queue the traveler\'s request into the elevator\'s "memory". Don\'t worry, we can unqueue this at the appropriate time. Make sure you pass the floor as a parameter!',
        nextRequestedFloor_name : 'earliest request',
        nextRequestedFloor_tip : 'Pick up the earliest (oldest) floor request from the elevator\'s "memory". This would be one that has been queued by queue request.',
        getCallDirection_name : 'get call direction',
        getCallDirection_tip : 'Pick up the direction of the call made by a person waiting for the elevator on this floor. In case both up and down directions have been requested on this floor, the older one is picked (i.e. the person who got there first)',
        getCallFloor_name : 'earliest call',
        getCallFloor_tip : 'Pick up the earliest (oldest) call request from the elevator\'s "memory". This would be one that represents the person who has been waiting the longest for the elevator to pick them up.',
        requestCount_name : 'request count',
        requestCount_tipS : 'Count of requests made by travelers inside the elevator and store in its "memory". Check that the count of requests is 1 or more before calling \'earliest request\'.',
        requestCount_tip : 'Count of requests made by travelers inside the elevator and store in its "memory". This procedure can be called with or without the floor parameter. If called without, it will give the count of all requests in the queue. If called with a floor parameter, it will give the count of requests on just that floor! Check that the count of requests is 1 or more before calling \'earliest request\'.',
        request_queue_not_empty_name : 'request queue not empty',
        request_queue_not_empty_tip : 'There are active requests made by travelers inside the elevator and those travelers haven\'t yet been taken to their destination floor. Use this in an \'if\' or \'else-if\' block to enter instructions based on this state.',
        request_queue_not_empty_curr_floor_name : 'traveler(s) to this floor',
        request_queue_not_empty_curr_floor_tip : 'There are one or more travelers inside the elevator who wish to get off at this floor. Use this in an \'if\' or \'else-if\' block to enter instructions based on this state.',
        dir_choice_name : 'elevator direction',
        dir_choice_tip : 'Use this in an \'if\' or \'if-else\' block to enter instructions based on the direction of the elevator (up or down).',
        elev_req_condn_name : 'elev has',
        elev_req_condn_tip : 'This block can be used to check for multiple conditions related to travel requests. One could check if there are any persons currently traveling on the elevator, or even if there are any travelers destined for the current floor. Use this in an \'if\' or \'else-if\' block to enter instructions based on this state.',
        call_req_condn_name : 'elev has',
        call_req_condn_tip : 'This block can be used to check for multiple conditions related to calls made by persons waiting on any floor. One could check if there are any persons waiting on any floor, or if there are any persons waiting on the current floor or even if there are any persons waiting on the current floor and traveling in the elevator\'s direction. Use this in an \'if\' or \'else-if\' block to enter instructions based on this state.',
        call_queue_not_empty_name : 'call queue not empty',
        call_queue_not_empty_tip : 'There are active calls made by persons waiting for the elevator on one or more floors and we haven\'t gone to pick them up yet. Use this in an \'if\' or \'else-if\' block to enter instructions based on this state.'
    },

    info: {
        1: '<p>The panel on the left of this game shows a building with 5 floors and a closed elevator door on each floor</p> </p><p>As soon as the game starts, you will see a person arrive on floor 1 and press the &quot;up&quot; button to call the elevator.</p></p>Your task is to fill in the &quot;elevator called&quot; procedure on the right to respond to that call.</p><p>After the person enters the elevator they will press a button indicating the desired floor they wish to travel to. Your also need to fill in the &quot;floor requested&quot; procedure on the right to respond to that request</p><p>Good luck and press the Help button if you want a hint</p> <p>Do not worry, it really needs only 2 lines of code to work! Once you move the blocks into the 2 procedures, you can view your code with &quot;View Code&quot; or run the game with &quot;Run Code&quot;</p><p>How exciting :)</p>',
        2: '<p>On this level, we make it a teeny bit difficult. You will see the person arrive on the second floor, while the elevator is idle on the first. Thats not too bad, you already know how to send the elevator to that floor, dont you?</p></p>We also add one more procedure to fill in this time, &quot;floor arrived&quot;. You need to fill in what one does when the elevator arrives at the floor, perhaps just open it?</p> <p>Good luck and press the Help button if you want a hint</p>',
        3: '<p>We had only one person in the first two levels. Now we have two, so double the fun!</p><p>You will see a person arrive on the first floor and travel to the fifth. Soon after you\'ve successfully moved that person to the destination a second person shows up, this time on the second floor!</p> <p>Good luck and press the Help button if you want a hint</p>',
        4: '<p>Now on this level, we will work with our first set of co-travelers!</p><p>We have two persons starting out on the first floor, but one going to the third and the second going all the way to the fifth.</p><p>Can you send them safely to their desired destinations?</p> <p>Good luck and press the Help button if you want a hint</p>',
        5: '<p>In the previous level, we did get both persons safely to their desired destinations, but it probably wasn\'t the best way ... we went all the way up to fifth and then down to third, just because the guy for fifth pushed the button first, getting to be first in queue!</p> Now on this level, let us optimize that so we\'ll do our stopover at third, letting that person get off and then make our way to fifth. That shouldn\'t be too difficult, right?</p><p>Good luck and press the Help button if you want a hint</p>',
        6: '<p>We now turn our attention to picking up travelers on the way to a destination. We haven\'t done that so far. In level 3 we had two persons, but they were sequential, the second called for the elevator just after the first was dropped off. In levels 4 and 5 we had two travelers, but they both got on on the first floor.</p> <p>Now, we\'ll have one person getting on the first floor going to the fifth and another getting on the fourth floor to also go to the fifth.</p> Can you pick up the second person along the way, as the first person travels up from the first to the fifth floor?</p><p>Good luck and press the Help button if you want a hint</p>',
        7: '<p>Let\'s get to a little more complexity with persons calling for the elevator, as compared to level 6. We handle a case where we pass by a floor, but do not pick up the person because they wish to travel in other direction.</p><p> Now, we\'ll have one person getting on the first floor going to the fifth and another getting on the fourth floor to go to the first floor.</p> Can you drop off the first person and then come back to the fourth floor to pick up the second person while they wait?</p><p>Good luck and press the Help button if you want a hint</p>',
        8: '<p>Now we get to the point where we handle all kinds of situations. You will have 18 persons arrive at various times across all 5 floors going to different destinations. It is going to be a busy day for our elevator!</p> However, do not worry, we have set the stage for this complexity by considering individual (and simpler) scenarios in previous levels; you now only have to put it all together!</p><p>Good luck and press the Help button if you want a hint</p>'
    },

    help: {
        1: '<p>In this simplest scenario, the elevator is already on the floor where the person arrives, so just open the elevator.</p><p>And when the person presses the button, we call &quot;floor requested&quot; in which case just go to the desired floor! Dont forget to pass the floor as the argument to the call ... </p>',
        2: '<p>In this case, the elevator is not already on the floor where the person arrives, so let us first send the elevator to that floor.</p><p>And when we arrive at a floor, lets just open the elevator. </p>',
        3: '<p>Here you need to deal with both cases, one when the elevator is on the floor where the person arriving is and also where it isn\'t.</p><p> This calls for an &quot;if-else&quot; block where you check if the floor the elevator is on, &quotat floor&quot; is the same as the floor from where the person called, &quot;floor&quot;.</p><p> If they are the same, just open the elevator, else go to that floor ... simple, innit?</p>',
        4: '<p>Since both persons get on the same floor, they are going to be pressing the buttons immediately, for floor 5 and floor 3.<p></p> You cannot just go to the floors as they get pressed. You need to \'save\' them in a queue. When the elevator door closes, you can see if there are any requests (Hint: use \'request queue is not empty\' in an \'if\' block) then send the elevator to that floor.</p><p>That way, each time the elevator door is closed, you will be processing the \'requests\' (Hint: use \'earliest request\' to get one at a time) till there are none left and all travelers have been dispatched to their destination!</p>',
        5: '<p>Rather than going straight to the floor based on the \'earliest request\' (like we did on level 4) let\'s just go one floor at a time.</p>To do that, add 1 to the current floor if the elevator direction is \'up\' or subtract 1 from the current floor in case the direction is \'down\'. (Hint: Use the Math blocks to do the arithmetic and the \'elevator direction\' in an \'if\' block to decide on add/subtract).</p><p> When we arrive at a floor, we see if there is anyone getting off here (Hint: use \'traveler(s) to this floor\' in an \'if\') and open the elevator if so; if not, do your arithmetic again to go one floor up or down as before!</p>',
        6: '<p>Much of your code stays the same from what you did in level 5, with one important difference.</p><p>When you arrive at the fourth floor, you need to answer the call, i.e. open the elevator. To do so, change the \'if-else\' you had on \'floor arrived\' to an \'if-elseif-else\' (i.e. a series of logic checks).</p><p> Check if there are any calls in the travel direction (Hint: use \'call in travel direction\' with \'if\') and if so, open the elevator.</p> Then check if there are travelers at this floor using the \'else if\' section of the block.</p>',
        7: '<p>Much of your code stays the same from what you did in level 6, but \'elevator door closed\' and \'floor arrived\' need to handle the case where there are no active requests, but there is an active call.</p><p>In \'elevator door closed\' if there are no travelers left in the elevator, you should check if there are active queued calls on any floor. If so, go to the floor which has the earliest call so you dont make any person wait unfairly..</p><p>In \'floor arrived\' add an \'else-if\' condition that the elevator has no travelers on it and has someone waiting for the elevator on this floor (Hint: use the \'and\' logical block to implement this). In such a case, you should open the elevator to let that person in',
        8: '<p>In \'elevator called\' check if the elevator is idle. If yes, and the elevator is already at the floor it has been called on, just open it. If not, go to that floor</p><p>In \'floor arrived\', stop and open the elevator if there are people on the elevator getting off or the persons waiting at that floor are going in the same direction as folks already in the elevator (and not yet at their destination). You should also open the elevator if everyone on it is getting off there and there are people wishing to get on (in any direction). If none of these conditions are met, keeping moving to the next floor. Note that you shouldn\'t stop at a floor if there are people waiting, but they want to go in the other direction, you\'d just be taking them for a long ride!</p><p>In \'elevator door closed\' if the elevator has any travelers in it, just keep going one floor ahead in the direction they want. If not, we have no more people in the elevator to take anywhere, check if there are any calls to process and if so, pick the one for the oldest (longest person waiting) and go straight to their floor.</p>'
    }
};
